### ISSUE TITLE
Local web server not working as documented, one needs to set webbase explicitly

### ISSUE THREAD

**Issue by milanaleksic** [JonahBraun/wago#4]
It would be nice if you could really default to current directory, I am not able to open any file unless I put webbase explicitly, as it's the only thing looked at in the startWebServer method https://github.com/JonahBraun/wago/blob/master/main.go#L246

    wago -web=':9933' -webbase=.

**Comment by JonahBraun** [comment]
Thanks for calling this out, that's what I get for not running all my tests on a "small update"! Release will come out soon.
