### ISSUE TITLE
using https://github.com/signintech/gopdf seems to cause sigterm

### ISSUE THREAD

**Issue by Karl01** [JonahBraun/wago#7]
Thanks for this great package, just one comment which is not urgent. When you use the gopdf package wago comes up wuith a  << ✏  Matched event: "/home/userpt18z97/proj40dev/hello.pdf": MODIFY
✏  Sending signal SIGTERM to command: go run src/main/main.go >> when writing the pdf to disc. If you just start the go program conventionally with "go run src/main/main.go" it does not happen.

KLR$ cat /usr/bin/g4
cd $HOME/proj40dev/;./wago -cmd='go run src/main/main.go' -daemon='main.go' -timer=35

[edit]
added ./pdf path for pdf files; with << ./wago -q -ignore='(/.pdf)' -cmd='go run src/main/main.g o' -daemon='main.go' -timer=35 >> the hello.pdf file now is ignored in the ./pdf path but wago continues to restart the program

**Comment by JonahBraun** [comment]
Hi @Karl01,

What you are doing will work, you just need to fix the regex in the ignore switch. Try: `-ignore='(.git|pdf)'`

So your entire command would be:
```Shell
wago -q -ignore='(.git|pdf)' -cmd='go run src/main/main.g o' -daemon='main.go' -timer=35
```

I'm assuming you are using git as well. Let me know if you still have issues!

Regex can get ignoring when listing multiple items. In the future I'd like to add support for gitignore style pattern matching.
